# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Approved'), (3, 'Rejected')], default=1)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review_site.Business')),
            ],
        ),
    ]
